<!DOCTYPE html>

<body>
<div>
    <label for="search-key">Search Key:</label>
    <input type="text" id="search-key" placeholder="Enter key to search">
</div>

<table class="data table" id="custom-config-table">
    <thead>
    <tr>
        <th>Parent Key</th>
        <th>Path</th>
        <th>Value</th>
        <th>Source Model</th>
    </tr>
    </thead>
    <tbody>
    <?php
    // Replace this PHP loop with your actual data
    foreach ($block->flattenConfigArray($block->getConfigArray()) as $data): ?>
        <tr>
            <td><?= $data['parent_key'] ?></td>
            <td><?= $data['key'] ?></td>
            <td><?= ($data['value'] == 1) ? 'Yes' : 'No' ?></td>
            <td><?= $data['source_model'] ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>


</body>
</htm
